# permissions for end users to view workspaceapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspaceapplication-viewer-role
rules:
- apiGroups:
  - components.truefoundry.io
  resources:
  - workspaceapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - components.truefoundry.io
  resources:
  - workspaceapplications/status
  verbs:
  - get
