# permissions for end users to view workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-viewer-role
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - components.truefoundry.io
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - components.truefoundry.io
  resources:
  - workspaces/status
  verbs:
  - get
