{{- range .Values.applications }}
---
apiVersion: components.truefoundry.io/v1alpha1
kind: WorkspaceApplication
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Name }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
