apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gw
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - {{ .Values.hostUrl }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - {{ .Values.hostUrl }}
      port:
        name: https
        number: 443
        protocol: HTTP