apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name  }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    app: {{ .Release.Name  }}
  type: ClusterIP