apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
spec:
  gateways:
    - {{ .Release.Name }}-gw
  hosts:
    - {{ .Values.hostUrl }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}-svc
            port:
              number: {{ .Values.port }}