apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerHubCreds }}
kind: Secret
metadata:
  name: image-pull-secret
  namespace: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson