apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Name }}
  name: deny-from-other-namespaces
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}