apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- if eq .Values.istioInjection "enabled" }}
    istio-injection: enabled
    {{- end }}
  annotations:
    k8s.titansoft.com/imagepullsecret-patcher-exclude: "true"
