truefoundry-workspace-template:
  enabled: true
  managedBy: servicefoundry
  dockerHubCreds: dummy
  istioInjection: "enabled"
  resourceQuota:
    limitsCpu: 10
    limitsMemory: 10Gi
    services: 10
grafana-tenant:
  enabled: false
